remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

title: Go-Geostat Documentation
description: A Go library for geostatistical analysis
show_downloads: true
google_analytics:

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - pkg/*.md 